[project]
name = "dino-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "farkaskid", email = "farkaskid.inbox@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
dino-runner = "dino_runner.main:run"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
